/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dabadex;

import org.junit.Test;
import static org.junit.Assert.*;

public class StartTest {
    @Test public void testStartHasALogger() {
        App classUnderTest = new Start();
        assertNotNull("Start should have a logger", classUnderTest.LOGGER);
    }
}
